#load_main_model: true
save_model: true
model:
  type: resnet50
dataset: imagenet
aug: DeepAA
deepaa:
  EXP: imagenet_1
augmentation_search_space: Not_used
cutout: -1
batch: 256
gpus: 8
epoch: 270
lr: .1
lr_schedule:
  type: 'resnet'
  warmup:
    multiplier: 8.0
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0001
  clip: 0
test_interval: 20

